config/routes.rb
Rails.application.routes.draw do
  resources :events
  namespace :admin do
    resources :shifts do
      collection do
        get :copy_shift #データの受け渡し
        get :confirmed_shift #確定されたシフトを表示させるメソッド
      end
      get '/registered', to: 'hope_shifts#registered'
    end
    resources :end_users
    resources :hope_shifts do
      get '/active', to: 'hope_shifts#active'
      get '/registered', to: 'hope_shifts#registered'
      patch :copy_update
    end
    get 'homes/top'
  end
  
    # 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

  #顧客用
# URL /end_users/sign_in ...
devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
  scope module: :public do
    resources :shifts
    resources :end_users
    resources :hope_shifts
    get 'homes/top'
  end

  resources :events
  get '/' => 'public/homes#top'
  get 'my_calendar', to: 'events#my_calendar'
  get '/end_users/my_page' => 'public/end_users#index'
  get '/end_users/edit' => 'public/end_users#edit'
  root to: 'top#index'
  
  #resources :shifts
  #resources :end_users
  #resources :admins
  #resources :hope_shifts


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shift.rb
class Shift < ApplicationRecord
    belongs_to :hope_shift
    belongs_to :admin
    
  def shift_title
    "<確定>" + hope_shift.end_user.name + "/" + "勤務:" + working_time_start.to_s + "-" + working_time_end.to_s + "時" + "/" + "休憩:" + break_time_start.to_s + "-" + break_time_end.to_s + "時"
  end
  
  def start_date
  end
  
  def end_date
  end
  
  def end_user
  end
  
  validates :break_time_start, presence: true
  validates :break_time_end, presence: true
  
end

app/controllers/admin/shifts_controller.rb
class Admin::ShiftsController < ApplicationController
  before_action :authenticate_admin!
  
  
    def index
     @hope_shifts = HopeShift.where(is_active: false).where(is_registered: false) # これで仮確定しているシフト希望を取得
     @shift = Shift.new
     @hope_shifts.each do |hope_shift|
       @hope_shift_working_time_start = hope_shift.working_time_start
       @hope_shift_working_time_end = hope_shift.working_time_end
       @hope_shift_date = hope_shift.date
     end
    end
    
    def show
     
    end
    
    def edit
     @shift = Shift.find(params[:id])
    end
    
    def create
      #byebug
        @shift = Shift.new(shift_params)
        @shift.admin_id = current_admin.id
        
        
        if @shift.save
          hope_shift = HopeShift.find(@shift.hope_shift_id) 
          hope_shift.update(is_registered: true) # 確定したシフトの作成
          Shift.update(notice_flag: false)
          flash[:success] = "登録に成功しました"
          redirect_to confirmed_shift_admin_shifts_path(@shift.id)
        else
          flash[:warning] = "入力内容を確認してください"
          redirect_to admin_shifts_path(@shift.id)
          
          #@hope_shifts = HopeShift.where(is_active: false).where(is_registered: false)
          #render :index
        end
    end
    
    def update
      @shift = Shift.find(params[:id])
        if @shift.update(shift_params)
          flash[:success] = "更新に成功しました"
          redirect_to confirmed_shift_admin_shifts_path
        else
          flash[:warning] = "入力内容を確認してください"
          redirect_to edit_admin_shift_path(@shift.id)
        end
    end
    
    def registered #いらない？
      @hope_shift = HopeShift.find(params["hope_shift_id"])
      @hope_shift.is_registered = true # 確定
      
      if @hope_shift.update(is_registered: true)
        flash[:success] = "更新に成功しました"
        redirect_to confirmed_shift_admin_shifts_path
      else
        flash[:warning] = "入力内容を確認してください"
        redirect_to admin_shifts_path
      end
    end
    
    def confirmed_shift
      @shifts = Shift.all # これで確定しているシフトを取得
       @shifts.each do |shift|
         @shift_working_time_start = shift.working_time_start
         @shift_working_time_end = shift.working_time_end
         @shift_date = shift.date
       end
    end
    
    def copy_shift
        @hope_shift = HopeShift.find(params["hope_shift_id"])
        @shift = Shift.new()
        @shift.hope_shift_id = @hope_shift.id
        @shift.admin_id = current_admin.id
        @shift.working_time_start = @hope_shift.working_time_start
        @shift.working_time_end = @hope_shift.working_time_end
        @shift.break_time_start = "00:00:00"
        @shift.break_time_end = "00:00:00"
        @shift.date = @hope_shift.date
        
        if @shift.save
          flash[:success] = "登録に成功しました"
          redirect_to admin_shifts_path(@shift.id)
        else
          flash[:warning] = "入力内容を確認してください"
          render :index
        end
    end
    
    def destroy # 確定シフトの削除
      @shift = Shift.find(params["id"])
      @shift.destroy
      redirect_to confirmed_shift_admin_shifts_path
    end
    
    private
  def shift_params
    params.require(:shift).permit(:admin_id, :hope_shift_id, :working_time_start, :working_time_end, :notice_flag, :break_time_start, :break_time_end, :date)
  end
end

app/helpers/admin/shifts_helper.rb
module Admin::ShiftsHelper
end

app/views/admin/shifts/comfirmed_shift.html.erb
<!-- 確定シフト一覧画面 -->
<div class="row" style="width:60%; margin:0 auto;">
<h4>確定シフト一覧</h4>
  <%= form_with model: @shift, url:admin_shifts_path, method: :post do |f| %>
    <table class="table table-bordered">
    	<tr>
    		<th>希望者</th>
    		<th>希望日時</th>
    		<th>労働開始時間</th>
    		<th>労働終了時間</th>
    		<th>休憩開始時間</th>
    		<th>休憩終了時間</th>
    	</tr>
  
      <% @shifts.each do |shift| %>
    	<tr>
    		<td><%= shift.end_user.name %></td>
          <td><%= shift.date %> <%= f.hidden_field :date, :value => @hope_shift_date %></td>
          <td><%= shift.working_time_start %> <%= f.hidden_field :working_time_start, :value => @shift_working_time_start %></td>
          <td><%= shift.working_time_end %> <%= f.hidden_field :working_time_end, :value => @shift_working_time_end %></td>
          <%# if hope_shift.shifts.first.present? then %>
            <td><%= shift_break_time_start %> <%= f.hidden_field :break_time_start, :value => @shift_break_time_start %></td>
            <td><%= shift_break_time_end %> <%= f.hidden_field :break_time_end, :value => @shift_break_time_end %></td>
          <%# else %>
          <%# end %>
          <td>
            <%= f.submit '登録', class:"btn btn-info btn-md" %>
            <%#= link_to "本登録", admin_shifts_path(@shift.id), methed: :post %>


          </td>
          <td><%= link_to "編集", edit_admin_shift_path(hope_shift.id ) %></td>
          <td><%= link_to "削除する", admin_shift_path(hope_shift.id), method: :delete %></td>
    	 </tr>
      <% end %>
    </table>
  <% end %>
</div>>

app/views/admin/shifts/confirmed_shift.html.erb
<!-- 確定シフト一覧画面 -->
 <div class="row" style="width:60%; margin:0 auto;">
<h4>確定シフト一覧</h4>
  <%= form_with model: @shift, url:admin_shifts_path do |f| %>
    <table class="table table-bordered">
    	<tr>
    		<th>希望者</th>
    		<th>希望日時</th>
    		<th>労働開始時間</th>
    		<th>労働終了時間</th>
    		<th>休憩開始時間</th>
    		<th>休憩終了時間</th>
    	</tr>
  
      <% @shifts.each do |shift| %>
    	<tr>
    		<td><%= shift.hope_shift.end_user.name %></td>
          <td><%= shift.date %> <%= f.hidden_field :date, :value => @hope_shift_date %></td>
          <td><%= shift.working_time_start %> <%= f.hidden_field :working_time_start, :value => @shift_working_time_start %></td>
          <td><%= shift.working_time_end %> <%= f.hidden_field :working_time_end, :value => @shift_working_time_end %></td>
          <%# if hope_shift.shifts.first.present? then %>
          <td><%= shift.break_time_start %> <%= f.hidden_field :break_time_start, :value => @shift_break_time_start %></td>
          <td><%= shift.break_time_end %> <%= f.hidden_field :break_time_end, :value => @shift_break_time_end %></td>
          <%# else %>
          <%# end %>
            <%#= f.submit '登録', class:"btn btn-info btn-md" %>
            <%#= link_to "本登録", admin_shifts_path(@shift.id), methed: :post %>
          <td><%= link_to "編集", edit_admin_shift_path(shift.id ) %></td>
          <td><%= link_to "削除する", admin_shift_path(shift.id), method: :delete %></td>
    	 </tr>
      <% end %>
    </table>
  <% end %>
</div>

<div id="calendar"></div> <!-- カレンダーを特定のページに読み込ませる -->

app/views/admin/shifts/edit.html.erb
<h1>管理者仮確定シフト編集ページ</h1>
<%= form_for @shift, url: admin_shift_path(@shift.id), method: :patch do |f| %>
  <%= f.date_select :date, {}, class: 'form-control' %>
  <%#= f.datetime_select :start_date, {}, class: 'form-control' %>

  <%#= f.datetime_select :end_date, {}, class: 'form-control' %>

  <%= f.number_field :working_time_start, in: 0..24 %>
  <%= f.number_field :working_time_end, in: 0..24 %>
  
     <%#= form_with model: @shift, url:admin_shift_path, method: :patch do |f| %>
    　<%#= f.number_field :break_time_start, in: 0..24 %>
      <%#= f.number_field :break_time_end, in: 0..24 %>
        <%#= f.submit "更新" %>
     <%# end %>
  
  <%#= f.fields_for :shift do |s| %>
    <%= f.number_field :break_time_start, in: 0..24 %>
    <%= f.number_field :break_time_end, in: 0..24 %>
  <%# end %>

  <%= f.submit "更新" %>
<% end %>

app/views/admin/shifts/index.html.erb
<!-- 仮確定シフト一覧画面 -->

<% if @shift.errors.any? %>
  <%= @shift.errors.count %>件のエラーが発生しました
  <ul>
    <% @shift.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="row" style="width:60%; margin:0 auto;">
<h4>仮確定シフト一覧</h4>

  <%= form_with model: @shift, url:admin_shifts_path, method: :post do |f| %>  
    <table class="table table-bordered">
    	<tr>
    		<th>希望者</th>
    		<th>希望日時</th>
    		<th>労働開始時間</th>
    		<th>労働終了時間</th>
    		
    		<!-- 休憩時間は空欄がデフォルトです。このページで設定してください -->
    		<th>休憩開始時間</th>
    		<th>休憩終了時間</th>
    	</tr>
  
      <% @hope_shifts.each do |hope_shift| %>
        
      	<tr>
      		<td><%= hope_shift.end_user.name %></td>
      		<%= f.hidden_field :hope_shift_id, :value => hope_shift.id %>
            <td><%= hope_shift.date %> <%= f.hidden_field :date, :value => @hope_shift_date %></td>
            <td><%= hope_shift.working_time_start %> <%= f.hidden_field :working_time_start, :value => @hope_shift_working_time_start %></td>
            <td><%= hope_shift.working_time_end %> <%= f.hidden_field :working_time_end, :value => @hope_shift_working_time_end %></td>
            <%# if hope_shift.shifts.first.present? then %>
              <td><%= f.number_field :break_time_start, in: 0..24 %></td>
              <td><%= f.number_field :break_time_end, in: 0..24 %></td>
            <%# else %>
              <td></td>
              <td></td>
            <%# end %>
            <td>
              <%= f.submit '登録', class:"btn btn-info btn-md" %>
              <%#= link_to "登録", admin_hope_shift_registered_path(hope_shift_id: hope_shift.id) %>
  
  
            </td>
            <td><%= link_to "編集", edit_admin_hope_shift_path(hope_shift.id ) %></td>
            <td><%= link_to "削除する", admin_hope_shift_path(hope_shift.id), method: :delete %></td>
      	 </tr>
          <% end %>
    </table>
  <% end %>
</div>

<div id="calendar"></div> <!-- カレンダーを特定のページに読み込ませる -->

app/views/admin/shifts/show.html.erb
<h1>確定シフト詳細</h1>
<!-- このページは使いません -->