config/routes.rb
Rails.application.routes.draw do
  resources :events
  namespace :admin do
    resources :shifts do
      collection do
        get :copy_shift #データの受け渡し
        get :confirmed_shift #確定されたシフトを表示させるメソッド
      end
      get '/registered', to: 'hope_shifts#registered'
    end
    resources :end_users
    resources :hope_shifts do
      get '/active', to: 'hope_shifts#active'
      get '/registered', to: 'hope_shifts#registered'
      patch :copy_update
    end
    get 'homes/top'
  end
  
    # 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

  #顧客用
# URL /end_users/sign_in ...
devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
  scope module: :public do
    resources :shifts
    resources :end_users
    resources :hope_shifts
    get 'homes/top'
  end

  resources :events
  get '/' => 'public/homes#top'
  get 'my_calendar', to: 'events#my_calendar'
  get '/end_users/my_page' => 'public/end_users#index'
  get '/end_users/edit' => 'public/end_users#edit'
  root to: 'top#index'
  
  #resources :shifts
  #resources :end_users
  #resources :admins
  #resources :hope_shifts


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_adminheader.html.erb
  <div id = "header">
      <%= link_to root_path do %>
      		<h1>NewShift</h1>
      <% end %>

      <% if admin_signed_in? %>
        <p style="text-align:right; padding: 10px 10px 0 0; color:#694D49;">
      	  ようこそ、
      		<%= current_admin.name %>
      		さん
      	</p>
      <% end %>

      <div id="box" style="margin: 0 auto 20px; text-align: center;">
      <!-- ログイン時表示される内容-->
      <% if admin_signed_in? %>
      	  <%= link_to 'シフト作成', admin_hope_shifts_path, class:"btn btn-primary text-dark bg-light" %>
      	  <%= link_to '仮確定シフト一覧', admin_shifts_path, class:"btn btn-primary text-dark bg-light" %>
      	  <%= link_to '確定シフト一覧', confirmed_shift_admin_shifts_path, class:"btn btn-primary text-dark bg-light" %>
          <%= link_to '従業員一覧', admin_end_users_path, class:"btn btn-primary text-dark bg-light" %>
      	  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"btn btn-primary text-dark bg-light" %>

      	<% else %>
      <!-- ログアウト時に表示される内容 -->
      	  <%= link_to '新規登録', new_end_user_registration_path %>
      	  <%= link_to 'ログイン', new_admin_session_path %>
      	<% end %>
      </div>
  </div>

app/views/layouts/_header.html.erb
<body>
       <div id="header" style="border-bottom:1px solid #dad7d7">
         
      <%= link_to root_path do %>
      		<h1>NewShift</h1>
      <% end %>

      <!-- 退会済みユーザーの場合は表示を変える。 -->
      	<% if end_user_signed_in? && current_end_user.is_deleted %>
      			<p style="text-align:right; padding: 10px 10px 0 0; color:#694D49;">
      				あなたは退会済みです
      			</p>
      	<% elsif end_user_signed_in? && !current_end_user.is_deleted %>
      			<p style="text-align:right; padding: 10px 10px 0 0; color:#694D49;">
      				ようこそ、
      				<%= link_to current_end_user.name, end_users_path %>
      				さん
      			</p>
      	<% end %>
      	
      <div id="box" style="margin: 0 auto 20px; text-align: center;">
        <% if end_user_signed_in? && current_end_user %>
        <!-- ログイン時表示される内容-->
          <%= link_to "マイページ", end_users_path, class:"btn btn-primary text-dark bg-light" %>
          <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class:"btn btn-primary text-dark bg-light" %>
        <% else %>
        <!-- ログアウト時に表示される内容 -->
          <%= link_to "新規登録", new_end_user_registration_path, class:"btn btn-primary text-dark bg-light" %>
          <%= link_to "ログイン", new_end_user_session_path, class:"btn btn-primary text-dark bg-light" %>
        <% end %>
        
        <% if admin_signed_in? %>
          <%= link_to admin_homes_top_path do %>
    				<%= current_admin.name %> (管理者ページ)
    			 <% end %>
			       <= 管理者ログイン中
        <% end %>
      </div>
      
    </div>  
    
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiftCreation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-turbolinks="false">
  <header>
        <% if admin_signed_in? %>
            <%= render 'layouts/adminheader' %>
        <% else %>
            <%= render 'layouts/header' %>
        <% end %>
  </header>
  
    <%# deivseのフラッシュメッセージを表示 %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
    <%= yield %>
      
  </body>
</html>